#Ce fichier contiens la config de base du serveur---
Pied:
    facebook: https://www.facebook.com/
    twitter: https://twitter.com/craftmywebsite
    youtube: https://www.youtube.com/channel/UCzkhnB95d0SCLU2zrTWEBOQ
    discord: https://discord.gg/cVw9UkU
All:
    money: Jeton
    atout1_nom: Battez-vous
    atout2_nom: Stuffez-vous
    atout3_nom: Créez votre empire
    atout1_text: Battez vous contre vos ennemis pour vous faire une réputation
    atout2_text: Récuperez le stuff de vos ennemis et utilisez le
    atout3_text: Recrutez des amis, faites vous des alliés et dominez sur le monde!
    logo: true
